gamification/modules/challenge/urls.py
from django.urls import path

from gamification.modules.challenge.views import ChallengeView
from gamification.modules.challenge.views import ListChallengeView
from gamification.modules.challenge.views import AssignChallengeView
from gamification.modules.challenge.views import DetailChallengeView
from gamification.modules.challenge.views import AcceptChallengeView
from gamification.modules.challenge.views import RejectChallengeView

app_name = "challenge"

urlpatterns = [
    path("challenge/", ChallengeView.as_view(), name="challenge"),
    path("challenge/<int:pk>/", DetailChallengeView.as_view(), name="challenge-detail"),
    path("list-challenge/", ListChallengeView.as_view(), name="list-challenge"),
    path("assign-challenge/", AssignChallengeView.as_view(), name="assign-challenge"),
    path("accept-challenge/<int:challenge>/<uuid:user>/", AcceptChallengeView.as_view(), name="accept-challenge"),
    path("reject-challenge/<int:challenge>/<uuid:user>/", RejectChallengeView.as_view(), name="reject-challenge"),
]

gamification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gamification.modules.user.urls")),
    path("", include("gamification.modules.challenge.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamification/modules/challenge/models.py
from django.db import models

from gamification.modules.user.models import User


class Challenge(models.Model):
    name = models.CharField(verbose_name="Nome", max_length=150)
    description = models.TextField(verbose_name="Descrição")
    banner = models.ImageField(verbose_name="Identidade visual", upload_to="challenges")
    rule = models.TextField(verbose_name="Regras")
    end_date = models.DateField(verbose_name="Data de término", null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Desafio"
        verbose_name_plural = "Desafios"


class UserChallenge(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_challenge", verbose_name="Usuário")
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name="user_challenge", verbose_name="Desafio")
    accepted = models.BooleanField(default=False, verbose_name="Desafio aceito")
    received_response = models.BooleanField(default=False, verbose_name="Recebeu resposta")

    class Meta:
        verbose_name = "Desafio do usuário"
        verbose_name_plural = "Desafios dos usuários"
        unique_together = ["user", "challenge"]

gamification/modules/challenge/forms.py
from django import forms

from django.core.validators import ValidationError

from PIL import Image

from gamification.modules.user.models import User

from gamification.modules.challenge.models import Challenge
from gamification.modules.challenge.models import UserChallenge

from gamification.modules.utils import add_placeholder

from datetime import date


class ChallengeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields["name"], "Digite o nome do desafio")
        add_placeholder(self.fields["description"], "Digite a descrição do desafio")
        add_placeholder(self.fields["rule"], "Digite as regras do desafio")
        add_placeholder(self.fields["end_date"], "Digite a data de término")

    class Meta:
        model = Challenge
        fields = ["name", "description", "banner", "rule", "end_date"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-input"}),
            "description": forms.Textarea(attrs={"class": "form-input"}),
            "rule": forms.Textarea(attrs={"class": "form-input"}),
        }

    end_date = forms.DateField(
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=("%Y-%m-%d",),
        required=False,
    )
    banner = forms.FileField(
        label="Identidade visual",
        widget=forms.FileInput(attrs={"class": "form-file-input", "accept": "image/*"}),
    )

    def clean_banner(self):
        banner = self.cleaned_data.get("banner")

        if not banner:
            raise ValidationError("O banner é obrigatório.")

        try:
            Image.open(banner)
        except IOError:
            raise ValidationError("O arquivo recebido não é uma imagem.")

        if banner.size > 5 * 1024 * 1024:
            raise ValidationError("A imagem não pode ter mais de 5MB.")

        return banner

    def clean_end_date(self):
        end_date = self.cleaned_data.get("end_date")
        if end_date:
            if end_date < date.today():
                raise ValidationError("A data de término não pode ser no passado.")
        return end_date

    def save(self, commit=True):
        challenge = super().save(commit=False)

        if commit:
            challenge.save()

        return challenge


class AssignChallengeForm(forms.ModelForm):
    class Meta:
        model = UserChallenge
        fields = ["user", "challenge",]

    user = forms.ModelChoiceField(
        queryset=User.objects.filter(role=2, is_active=True),
        widget=forms.Select(attrs={"class": "form-input"}),
    )
    challenge = forms.ModelChoiceField(
        queryset=Challenge.objects.all(),
        widget=forms.Select(attrs={"class": "form-input"}),
    )

    def clean_challenge(self):
        challenge = self.cleaned_data.get("challenge")
        end_date = challenge.end_date

        if challenge is None or challenge == "":
            raise ValidationError("O desafio inexistente.")

        if end_date:
            if end_date < date.today():
                raise ValidationError("O desafio já terminou.")

        return challenge


    def clean(self):
        cleaned_data = super().clean()
        user = cleaned_data.get("user")
        challenge = cleaned_data.get("challenge")

        if UserChallenge.objects.filter(user=user, challenge=challenge).exists():
            raise ValidationError("O usuário já possui esse desafio.")

        return cleaned_data

    def save(self, commit=True):
        user_challenge = super().save(commit=False)

        if commit:
            user_challenge.save()

        return user_challenge

gamification/modules/challenge/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from django.http import HttpResponseForbidden

from django.views import View
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from gamification.modules.user.models import User

from gamification.modules.challenge.models import Challenge
from gamification.modules.challenge.models import UserChallenge

from gamification.modules.challenge.forms import ChallengeForm
from gamification.modules.challenge.forms import AssignChallengeForm


@method_decorator(login_required(login_url="user:login"), name="get")
@method_decorator(login_required(login_url="user:login"), name="post")
class ChallengeView(View):
    def get(self, request):
        return render(
            request=request,
            template_name="challenge.html",
            context={"form": ChallengeForm()},
        )

    def post(self, request):
        form = ChallengeForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
        else:
            return render(
                request, template_name="challenge.html", context={"form": form}
            )

        return redirect("challenge:list-challenge")


@method_decorator(login_required(login_url="user:login"), name="get")
class ListChallengeView(ListView):
    model = Challenge
    template_name = "list_challenge.html"
    ordering = ["id"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "challenges_pending_acceptance": Challenge.objects.filter(
                    user_challenge__user=self.request.user,
                    user_challenge__accepted=False,
                    user_challenge__received_response=False,
                ).order_by("-end_date"),
                "challenges": Challenge.objects.filter(
                    user_challenge__user=self.request.user,
                    user_challenge__accepted=False,
                    user_challenge__received_response=False,
                ).order_by("-end_date").union(Challenge.objects.filter(
                    user_challenge__user=self.request.user,
                    user_challenge__accepted=True,
                    user_challenge__received_response=True,
                )) if self.request.user.role == 2 else Challenge.objects.all().order_by("-end_date"),
            }
        )
        return context


@method_decorator(login_required(login_url="user:login"), name="get")
@method_decorator(login_required(login_url="user:login"), name="post")
class DetailChallengeView(View):
    def get(self, request, pk):
        challenge = get_object_or_404(Challenge, pk=pk)
        form = ChallengeForm(instance=challenge)
        return render(
            request=request,
            template_name="challenge.html",
            context={"form": form, "challenge": challenge, "users": User.objects.filter(user_challenge__accepted=True, user_challenge__challenge=challenge)},
        )

    def post(self, request, pk):
        challenge = get_object_or_404(Challenge, pk=pk)
        form = ChallengeForm(request.POST, request.FILES, instance=challenge)

        if form.is_valid():
            form.save()
        else:
            return render(
                request,
                template_name="challenge.html",
                context={"form": form, "challenge": challenge},
            )

        return redirect("challenge:challenge-detail", pk=pk)


@method_decorator(login_required(login_url="user:login"), name="get")
@method_decorator(login_required(login_url="user:login"), name="post")
class AssignChallengeView(View):
    def get(self, request):
        return render(
            request=request,
            template_name="assign_challenge.html",
            context={"form": AssignChallengeForm()},
        )

    def post(self, request):
        form = AssignChallengeForm(request.POST)

        if form.is_valid():
            form.save()
        else:
            return render(
                request, template_name="assign_challenge.html", context={"form": form},
            )

        return redirect("challenge:list-challenge")


class AcceptChallengeView(View):
    def get(self, request, challenge, user):
        challenge = get_object_or_404(UserChallenge, challenge=challenge, user=user)

        if request.user != challenge.user:
            return HttpResponseForbidden("Você não está cadastrado nesse desafio.")

        challenge.accepted = True
        challenge.received_response = True
        challenge.save()

        return redirect("challenge:list-challenge")
class RejectChallengeView(View):
    def get(self, request, challenge, user):
        challenge = get_object_or_404(UserChallenge, challenge=challenge, user=user)

        if request.user != challenge.user:
            return HttpResponseForbidden("Você não está cadastrado nesse desafio.")

        challenge.accepted = False
        challenge.received_response = True
        challenge.save()

        return redirect("challenge:list-challenge")

gamification/modules/challenge/templates/assign_challenge.html
{% extends 'global/base_template.html' %}
{% block style %}
    .container {
        max-width: 600px;
        width: 100%;
        padding: 20px;
        box-sizing: border-box;
        text-align: center;
        margin: 0 auto;
    }
    .form-container {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
        text-align: left;
    }
    .form-container label {
        display: block;
        margin-bottom: 10px;
    }
    .form-container input[type="text"],
    .form-container select {
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border: 1px solid #007bb5;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 15px;
        outline: none;
    }
    .form-container select {
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        background-color: white;
        background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="%23007bb5"><path d="M7 10l5 5 5-5z"/></svg>');
        background-repeat: no-repeat;
        background-position: right 10px center;
        padding-right: 30px;
        cursor: pointer;
    }
    .form-container button {
        background-color: #007bff;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        display: block;
        margin: 0 auto;
        transition: background-color 0.3s ease;
    }
    .form-container button:hover {
        background-color: #0056b3;
    }
{% endblock style %}

{% block content %}
<div class="container">
    <div class="form-container">
        <h2>Inserir usuário no desafio</h2>
        <form action="{% url 'challenge:assign-challenge' %}" method="post">
            {% csrf_token %}
            <label>Selecione o Usuário:</label>
            {{ form.user }}

            <label>Selecione o Desafio:</label>
            {{ form.challenge }}

            <button type="submit">Atribuir Desafio</button>
        </form>
    </div>
</div>
{% endblock content %}

gamification/modules/challenge/templates/challenge.html
{% extends 'global/base_template.html' %}
{% block style %}
    .main-container {
        display: flex;
        justify-content: space-between;
    }

    .container {
        max-width: 600px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 30px;
        margin: 50px auto;
        flex: 1;
    }

    .user-table {
        max-width: 600px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 30px;
        margin: 50px auto;
        flex: 1;
        margin-right: 20px;
    }

    h2 {
        color: #007bff;
        text-align: center;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #ddd;
    }

    th, td {
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-label {
        color: #007bff;
        font-weight: bold;
        display: block;
        margin-bottom: 8px;
    }

    .form-input {
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border: 1px solid #007bff;
        border-radius: 5px;
        box-sizing: border-box;
    }

    .form-file-label {
        display: inline-block;
        width: 96.5%;
        padding: 10px;
        background-color: #ffffff;
        color: #007bff;
        text-align: center;
        border: 1px solid #007bff;
        border-radius: 5px;
        cursor: pointer;
    }

    .form-file-label:hover {
        background-color: #007bff;
        color: #ffffff;
    }

    .form-file-input {
        display: none;
    }

    .form-submit {
        background-color: #007bff;
        color: #ffffff;
        border: none;
        padding: 12px 20px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    .form-submit:hover {
        background-color: #0056b3;
    }

    img {
        max-width: 100%;
        height: auto;
    }
{% endblock style %}

{% block content %}
<div class="main-container">
    <div class="container">
        {% if not challenge %}
        <h2>Criar Desafio</h2>
        <form action="{% url 'challenge:challenge' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
                <ul class="errorlist">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="form-group">
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.description }}
            </div>
            <div class="form-group">
                {{ form.rule }}
            </div>
            <div class="form-group">
                <label for="create_banner" class="form-file-label">Escolha um arquivo</label>
                <input type="file" name="banner" id="create_banner" class="form-file-input">
            </div>
            <div class="form-group">
                <input type="date" id="create_end_date" name="end_date" class="form-input">
            </div>
            <div class="form-group">
                <input type="submit" value="Criar Desafio" class="form-submit">
            </div>
        </form>
        {% elif perms.user.can_update_challenge %}
        <h2>Atualizar Desafio</h2>
        <form action="{% url 'challenge:challenge-detail' challenge.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
                <ul class="errorlist">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="form-group">
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.rule }}
            </div>
            <div class="form-group">
                {{ form.description }}
            </div>
            <div class="form-group">
                <img src="{{ challenge.banner.url }}" alt="Challenge banner">
                <label for="update_banner" class="form-file-label">Escolha um arquivo</label>
                <input type="file" name="banner" id="update_banner" class="form-file-input">
            </div>
            <div class="form-group">
                <input type="date" id="update_end_date" name="end_date" class="form-input" value="{{ challenge.end_date|date:'Y-m-d' }}">
            </div>

            <div class="form-group">
                <input type="submit" value="Atualizar Desafio" class="form-submit">
            </div>
        </form>
        {% else %}
        <h2>Detalhes do Desafio</h2>
        <div class="form-group">
            <label for="name" class="form-label">Nome:</label>
            <input type="text" id="name" class="form-input" value="{{ challenge.name }}" readonly>
        </div>
        <div class="form-group">
            <label for="description" class="form-label">Descrição:</label>
            <textarea id="description" class="form-input" rows="5" readonly>{{ challenge.description }}</textarea>
        </div>
        <div class="form-group">
            <label for="rule" class="form-label">Regras:</label>
            <textarea id="rule" class="form-input" rows="5" readonly>{{ challenge.rule }}</textarea>
        </div>
        <div class="form-group">
            <label for="banner" class="form-label">Banner:</label>
            <img src="{{ challenge.banner.url }}" id="banner" alt="Challenge banner">
        </div>
            {% if challenge.end_date %}
            <div class="form-group">
                <label for="end_date" class="form-label">Data de encerramento:</label>
                <input type="text" id="end_date" class="form-input" value="{{ challenge.end_date }}" readonly>
            </div>
            {% endif %}
        {% endif %}
    </div>
    {% if perms.user.can_view_assigned_challenge %}
    <div class="user-table">
            <h2>Usuários no Desafio</h2>
            <table>
                <thead>
                    <tr>
                        <th>Nome de Usuário</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
    {% endif %}
</div>
{% endblock content %}

gamification/modules/challenge/templates/list_challenge.html
{% extends 'global/base_template.html' %}
{% block style %}
    .container {
        display: flex;
        justify-content: center; /* Centraliza conteúdo */
        align-items: flex-start;
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
        box-sizing: border-box;
    }
    .desafios-container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        width: 70%;
        justify-content: center; /* Centraliza os desafios */
    }
    .desafio {
        width: calc(33.33% - 20px);
        margin-bottom: 20px;
        box-sizing: border-box;
        overflow: hidden;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .desafio .imagem {
        background-size: cover;
        background-position: center;
        height: 200px;
        position: relative;
    }
    .desafio .overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        opacity: 0.7;
        transition: opacity 0.3s ease;
    }
    .desafio:hover .overlay {
        opacity: 0.9;
    }
    .desafio .texto {
        position: absolute;
        bottom: 20px;
        left: 20px;
        right: 20px;
        color: #ffffff;
        text-align: center;
        z-index: 1;
    }
    .desafio h2 {
        margin: 0;
        font-size: 1.5em;
    }
    .desafio p {
        margin: 10px 0 0;
    }
    .lista-desafios {
        width: 30%;
        padding: 20px;
        box-sizing: border-box;
        background-color: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        position: sticky;
        top: 20px;
        right: 0;
    }
    .lista-desafios h3 {
        font-size: 1.2em;
        margin-bottom: 10px;
    }
    .lista-desafios ul {
        list-style-type: none;
        padding: 0;
        margin: 0;
    }
    .lista-desafios li {
        margin-bottom: 10px;
        padding: 10px;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        background-color: #ffffff;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .lista-desafios .btn-group {
        display: flex;
        gap: 10px;
    }
    .lista-desafios .btn-aceitar, .lista-desafios .btn-recusar {
        padding: 8px 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        transition: background-color 0.3s ease;
        text-decoration: none; /* Transforma botões em links */
    }
    .lista-desafios .btn-aceitar {
        background-color: #007bff;
        color: white;
    }
    .lista-desafios .btn-recusar {
        background-color: #dc3545;
        color: white;
    }
    .lista-desafios .btn-aceitar:hover, .lista-desafios .btn-recusar:hover {
        filter: brightness(85%);
    }
    .no-challenges {
        background-color: #fff;
        padding: 40px;
        border-radius: 15px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 400px;
        text-align: center;
        margin: 0 auto;
        margin-top: 20px;
    }
{% endblock style %}

{% block content %}
<div class="container">
    {% if challenges %}
    <div class="desafios-container">
        {% for challenge in challenges %}
            <div class="desafio">
                <div class="imagem" style="background-image: url('{{ challenge.banner.url }}');">
                    <a href="{% url 'challenge:challenge-detail' challenge.id %}">
                        <div class="overlay"></div>
                        <div class="texto">
                            <h2>{{ challenge.name }}</h2>
                            <p>{{ challenge.description }}</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="no-challenges">
        <p>Não existem desafios lançados.</p>
    </div>
    {% endif %}

    {% if perms.user.can_accept_challenge %}
    <div class="lista-desafios">
        <h3>Desafios a serem aceitos:</h3>
        <ul>
            {% for challenge in challenges_pending_acceptance %}
            <li>
                {{ challenge.name }}
                <div class="btn-group">
                    <a href="{% url 'challenge:accept-challenge' challenge.id request.user.id %}" class="btn-aceitar">Aceitar</a>
                    <a href="{% url 'challenge:reject-challenge' challenge.id request.user.id %}" class="btn-recusar">Recusar</a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock content %}