gamification/modules/challenge/urls.py
from django.urls import path

from gamification.modules.challenge.views import ChallengeView
from gamification.modules.challenge.views import ListChallengeView
from gamification.modules.challenge.views import AssignChallengeView
from gamification.modules.challenge.views import DetailChallengeView
from gamification.modules.challenge.views import AcceptChallengeView
from gamification.modules.challenge.views import RejectChallengeView

app_name = "challenge"

urlpatterns = [
    path("challenge/", ChallengeView.as_view(), name="challenge"),
    path("challenge/<int:pk>/", DetailChallengeView.as_view(), name="challenge-detail"),
    path("list-challenge/", ListChallengeView.as_view(), name="list-challenge"),
    path("assign-challenge/", AssignChallengeView.as_view(), name="assign-challenge"),
    path("accept-challenge/<int:challenge>/<uuid:user>/", AcceptChallengeView.as_view(), name="accept-challenge"),
    path("reject-challenge/<int:challenge>/<uuid:user>/", RejectChallengeView.as_view(), name="reject-challenge"),
]

gamification/modules/user/urls.py
from django.urls import path

from gamification.modules.user.views import LoginView
from gamification.modules.user.views import logout_view
from gamification.modules.user.views import AccountView
from gamification.modules.user.views import ListAccountView
from gamification.modules.user.views import UpdateAccountView
from gamification.modules.user.views import DeleteAccountView

app_name = "user"

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("account/", AccountView.as_view(), name="account"),
    path("users/", ListAccountView.as_view(), name="list-users"),
    path("profile/<uuid:pk>/", UpdateAccountView.as_view(), name="profile"),
    path("delete/<uuid:pk>/", DeleteAccountView.as_view(), name="delete-account"),
]

gamification/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gamification.modules.user.urls")),
    path("", include("gamification.modules.challenge.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamification/modules/user/models.py
import uuid
from django.db import models

from django.contrib.auth.models import Permission
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class RoleChoices(models.IntegerChoices):
        ADMIN = 1, "Admin"
        BROKER = 2, "Broker"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    cpf = models.CharField(max_length=14, unique=True)
    birth_date = models.DateField()
    phone = models.CharField(max_length=11)
    role = models.IntegerField(choices=RoleChoices.choices, default=RoleChoices.BROKER)
    user_permission = models.ManyToManyField(
        Permission, blank=True, related_name="custom_permissions"
    )

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"
        permissions = [
            ("can_view_assigned_challenge", "Can view assigned challenges"),
            ("can_accept_challenge", "Accept to participate in the challenge"),
            ("can_manage_user", "Can manage user"),
            ("can_create_challenge", "Can create challenge"),
            ("can_update_challenge", "Can update challenge"),
            ("can_set_challenge", "Can set challenge"),
        ]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

gamification/modules/user/forms.py
from django import forms

from django.contrib.auth.models import Permission
from django.core.validators import ValidationError

from django.contrib.auth.hashers import check_password

from gamification.modules.utils import add_placeholder
from gamification.modules.utils import strong_password
from gamification.modules.user.models import User

from datetime import date


class UserCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields["username"], "Digite seu nome de usuário")
        add_placeholder(self.fields["cpf"], "Digite seu cpf")
        add_placeholder(self.fields["password"], "Digite sua senha")
        add_placeholder(self.fields["password1"], "Confirme sua senha")
        add_placeholder(self.fields["first_name"], "Digite seu primeiro nome")
        add_placeholder(self.fields["last_name"], "Digite seu último nome")
        add_placeholder(self.fields["email"], "Digite seu email")
        add_placeholder(self.fields["phone"], "Digite seu telefone")
        add_placeholder(self.fields["birth_date"], "Digite sua data de nascimento")

    date_joined = forms.DateField(
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=("%Y-%m-%d",),
        required=False,
    )
    username = forms.CharField(
        label="Username",
        help_text=(
            "Username must have letters, numbers or one of those @.+-_. "
            "The length should be between 4 and 150 characters."
        ),
        error_messages={
            "required": "This field must not be empty",
            "min_length": "Username must have at least 4 characters",
            "max_length": "Username must have less than 150 characters",
        },
        min_length=4,
        max_length=150,
    )
    first_name = forms.CharField(
        error_messages={"required": "Write your first name"}, label="First name"
    )
    last_name = forms.CharField(
        error_messages={"required": "Write your last name"}, label="Last name"
    )
    email = forms.EmailField(
        error_messages={"required": "E-mail is required"},
        label="E-mail",
        help_text="The e-mail must be valid.",
    )
    birth_date = forms.DateField(
        widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=("%Y-%m-%d",),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        validators=[strong_password],
        error_messages={
            "required": "Password is required",
        },
        label="Password",
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(),
        label="Password2",
        error_messages={"required": "Please, repeat your password"},
    )

    def clean_cpf(self):
        cpf = self.cleaned_data.get("cpf", "")
        cpf = cpf.replace(".", "").replace("-", "")

        exists = User.objects.filter(cpf=cpf).exists()

        if exists:
            raise ValidationError(
                "User CPF is already in use",
                code="invalid",
            )

        return cpf

    def clean_email(self):
        email = self.cleaned_data.get("email", "")
        exists = User.objects.filter(email=email).exists()

        if exists:
            raise ValidationError(
                "User e-mail is already in use",
                code="invalid",
            )

        return email

    def clean(self):
        cleaned_data = super().clean()
        user_permission = [
            "can_view_assigned_challenge",
            "can_accept_challenge",
        ]
        permissions = Permission.objects.filter(codename__in=user_permission)
        cleaned_data.update(
            {
                "is_superuser": False,
                "is_staff": False,
                "is_active": True,
                "user_permission": permissions,
                "date_joined": date.today(),
            }
        )

        role = cleaned_data.get("role", 2)
        if role == 1:
            user_permission = [
                "can_manage_user",
                "can_create_challenge",
                "can_update_challenge",
                "can_set_challenge",
            ]
            permissions = Permission.objects.filter(codename__in=user_permission)
            cleaned_data["user_permission"] = permissions

        password = cleaned_data.get("password", "")
        password1 = cleaned_data.get("password1", "")

        if password != password1:
            self.add_error("password1", "Passwords must match")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
            permissions = self.cleaned_data.get("user_permission")
            for permission in permissions:
                user.user_permissions.add(permission)
            user.save()

        return user

    class Meta:
        model = User
        fields = "__all__"


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "password",
            "email",
            "cpf",
            "phone",
        ]

    password = forms.CharField(
        widget=forms.PasswordInput(),
        validators=[strong_password],
        required=False,
        label="Password",
    )


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields["username"], "Digite seu nome de usuário")
        add_placeholder(self.fields["password"], "Digite sua senha")

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

gamification/modules/user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.urls import reverse
from django.urls import reverse_lazy

from gamification.modules.user.forms import LoginForm
from gamification.modules.user.forms import UserCreationForm
from gamification.modules.user.forms import UserChangeForm
from gamification.modules.user.models import User


def logout_view(request):
    logout(request)
    return redirect(reverse("user:login"))


class LoginView(View):
    def get(self, request):
        return render(
            request=request, template_name="login.html", context={"form": LoginForm()}
        )

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            authenticated_user = authenticate(
                username=form.cleaned_data.get("username", ""),
                password=form.cleaned_data.get("password", ""),
            )

            if authenticated_user is not None:
                login(request, authenticated_user)
            else:
                return redirect(reverse("user:login"))
        else:
            return redirect(reverse("user:login"))
        return redirect(reverse("challenge:list-challenge"))


class AccountView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse("challenge:list-challenge"))
        return render(
            request=request,
            template_name="account.html",
            context={"form": UserCreationForm()},
        )

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
        else:
            return render(request, template_name="account.html", context={"form": form})

        return redirect(reverse("user:login"))


@method_decorator(login_required(login_url="user:login"), name="get")
class ListAccountView(ListView):
    model = User
    template_name = "list_users.html"
    context_object_name = "users"


@method_decorator(login_required(login_url="user:login"), name="get")
class UpdateAccountView(UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = "profile.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        password = form.cleaned_data.get("password")
        if password and password != "":
            user.set_password(password)
        else:
            user.password = self.get_object().password
        user.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        user = get_object_or_404(User, pk=pk)
        context["form"] = UserChangeForm(instance=user)
        return context

    def get_success_url(self):
        return reverse("user:profile", kwargs={"pk": self.kwargs.get("pk")})


@method_decorator(login_required(login_url="user:login"), name="post")
class DeleteAccountView(DeleteView):
    model = User
    context_object_name = "user"
    template_name = "delete_account.html"

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        user.delete()

        return redirect(reverse("user:list-users"))

gamification/modules/user/templates/account.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação de Usuário</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #e0f7fa;
        }

        .signup-container {
            background-color: #fff;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
            text-align: center;
            margin: 40px 20px;
        }

        .signup-container h2 {
            margin-bottom: 20px;
            font-size: 24px;
            color: #007bb5;
        }

        .signup-container input, .signup-container select {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #007bb5;
            border-radius: 25px;
            box-sizing: border-box;
            background-color: #fff;
        }

        .signup-container button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 25px;
            background-color: #007bb5;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

        .signup-container button:hover {
            background-color: #005f87;
        }

        .signup-container .login-link {
            margin-top: 20px;
            display: block;
            color: #007bb5;
            text-decoration: none;
        }

        .signup-container .login-link:hover {
            text-decoration: underline;
        }

        @media (max-width: 480px) {
            .signup-container {
                padding: 20px;
                margin: 20px 10px;
            }

            .signup-container h2 {
                font-size: 20px;
            }

            .signup-container input, .signup-container select, .signup-container button {
                padding: 8px;
                font-size: 14px;
            }

            .signup-container .login-link {
                font-size: 14px;
            }
        }
    </style>
</head>
<body>
    <div class="signup-container">
        <h2>Criação de Usuário</h2>
        {% if form.errors %}
            <ul class="errorlist">
                {% for field in form %}
                    {% for error in field.errors %}
                        <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        {% if not user.is_authenticated %}
            <form action="{% url 'user:account' %}" method="post">
                {% csrf_token %}
                {{ form.username }}
                {{ form.cpf }}
                {{ form.password }}
                {{ form.password1 }}
                {{ form.email }}
                {{ form.first_name }}
                {{ form.last_name }}
                {{ form.birth_date }}
                {{ form.role }}
                {{ form.phone }}
                <button type="submit">Criar Conta</button>
            </form>
            <a href="{% url 'user:login' %}" class="login-link">Já tem uma conta? Entrar</a>
        {% else %}
            <p>Você já possui uma conta.</p>
            <a href="{% url 'user:logout' %}">Sair</a>
        {% endif %}
    </div>
</body>
</html>

gamification/modules/user/templates/list_users.html
{% extends 'global/base_template.html' %}

{% block style %}
    .container {
        max-width: 900px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 30px;
        margin: 50px auto;
    }

    h2 {
        color: #007bff;
        text-align: center;
        margin-bottom: 30px;
    }

    .user-box {
        background-color: rgba(0, 0, 0, 0.05); /* Fumaça no fundo */
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .user-info {
        flex: 1;
    }

    .user-actions {
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .user-actions a {
        text-decoration: none;
        color: #007bff;
        padding: 5px 10px;
        border-radius: 4px;
        transition: background-color 0.3s;
    }

    .user-actions a:hover {
        background-color: #e0e0e0;
    }

    .user-actions a.delete,
    .user-actions form button.delete {
        color: #ffffff;
        background-color: #ff4d4d;
        padding: 5px 10px;
        border-radius: 4px;
        border: none;
        cursor: pointer;
        display: flex;
        align-items: center;
    }

    .user-actions a.delete:hover,
    .user-actions form button.delete:hover {
        background-color: #ff1a1a;
    }

    .user-actions a.edit {
        color: #ffa500;
    }

    .user-actions a.view {
        color: #007bff;
    }

    .icon {
        margin-right: 5px;
    }
{% endblock style %}

{% block content %}
<div class="container">
    <h2>Lista de Usuários</h2>
    {% for user in users %}
    <div class="user-box">
        <div class="user-info">
            <p><strong>Nome de Usuário:</strong> {{ user.username }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
        </div>
        <div class="user-actions">
            <a href="{% url 'user:profile' user.id %}" class="view">
                <span class="icon">👁️</span> Visualizar
            </a>
            <form action="{% url 'user:delete-account' user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="delete">
                <span class="icon">🗑️</span> Deletar Conta
            </button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

gamification/modules/user/templates/login.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #e0f7fa;
        }

        .login-container {
            background-color: #fff;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
        }

        .login-container h2 {
            margin-bottom: 20px;
            font-size: 24px;
            color: #007bb5;
        }

        .login-container input {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #007bb5;
            border-radius: 25px;
            box-sizing: border-box;
        }

        .login-container button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 25px;
            background-color: #007bb5;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .login-container button:hover {
            background-color: #005f87;
        }

        .login-container a {
            display: block;
            margin-top: 20px;
            color: #007bb5;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease, text-decoration 0.3s ease;
        }

        .login-container a:hover {
            color: #005f87;
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h2>Login</h2>
        {% if not user.is_authenticated %}
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                {{ form.username }}
                {{ form.password }}
                <button type="submit">Entrar</button>
            </form>
            <a href="{% url 'user:account' %}" class="signup-link">Criar conta</a>
        {% else %}
            <p>Você já está logado.</p>
            <a href="{% url 'challenge:list-challenge' %}" class="signup-link">Listagem dos desafios</a>
            <a href="{% url 'user:logout' %}" class="signup-link">Sair</a>
        {% endif %}
    </div>
</body>
</html>

gamification/modules/user/templates/profile.html
{% extends 'global/base_template.html' %}

{% block style %}
    .container {
        max-width: 900px;
        background-color: #ffffff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        padding: 30px;
        margin: 50px auto;
        margin-bottom: 50px; /* Espaço extra no final do container */
    }

    h2 {
        color: #007bff;
        text-align: center;
        margin-bottom: 30px;
    }

    .user-box {
        background-color: rgba(0, 0, 0, 0.05); /* Fumaça no fundo */
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .user-info {
        flex: 1;
        text-align: center; /* Centraliza o texto */
    }

    .profile-picture {
        border-radius: 50%;
        max-width: 150px;
        margin-bottom: 20px;
    }

    .profile-info {
        margin-bottom: 20px;
    }

    .profile-info span {
        display: block;
        font-weight: bold;
        color: #333333;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-group label {
        display: block;
        font-weight: bold;
        margin-bottom: 8px;
    }

    .form-group input, .form-group select, .form-group textarea {
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border: 1px solid #007bff;
        border-radius: 5px;
        box-sizing: border-box;
    }

    .form-submit {
        background-color: #007bff;
        color: #ffffff;
        border: none;
        padding: 12px 20px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    .form-submit:hover {
        background-color: #0056b3;
    }

    .cancel-link {
        display: block;
        text-align: center;
        margin-top: 20px;
        text-decoration: none;
        color: #007bff;
    }

    .user-actions {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-top: 20px;
    }

    .user-actions a {
        text-decoration: none;
        color: #007bff;
        padding: 10px 20px;
        border-radius: 4px;
        transition: background-color 0.3s;
    }

    .user-actions a:hover {
        background-color: #e0e0e0;
    }

    .user-actions a.delete,
    .user-actions form button.delete {
        color: #ffffff;
        background-color: #ff4d4d;
        padding: 5px 10px;
        border-radius: 4px;
        border: none;
        cursor: pointer;
        display: flex;
        align-items: center;
    }

    .user-actions a.delete:hover,
    .user-actions form button.delete:hover {
        background-color: #ff1a1a;
    }

    .user-actions a.back {
        color: #007bff;
    }

    .icon {
        margin-right: 5px;
    }
{% endblock style %}

{% block content %}
<div class="container">
    <h2>Informações do usuário</h2>
    <div class="user-box">
        <div class="user-info">
            <form action="{% url 'user:profile' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Nome de Usuário:</label>
                    <input type="text" id="username" name="username" value="{{ user.username }}" required readonly>
                </div>
                <div class="form-group">
                    <label for="cpf">CPF:</label>
                    <input type="text" id="cpf" name="cpf" value="{{ user.cpf }}" required readonly>
                </div>
                <div class="form-group">
                    <label for="name">Nome:</label>
                    <input type="text" id="name" name="first_name" value="{{ user.first_name }}" required>
                </div>
                <div class="form-group">
                    <label for="last_name">Sobrenome:</label>
                    <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}" required>
                </div>
                <div class="form-group">
                    <label for="password">Senha:</label>
                    <input type="password" id="password" name="password" value="">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" value="{{ user.email }}" required>
                </div>
                <div class="form-group">
                    <label for="phone">Telefone:</label>
                    <input type="text" id="phone" name="phone" value="{{ user.phone }}" required>
                </div>
                <button type="submit" class="form-submit">Salvar Alterações</button>
            </form>
        </div>
    </div>
    <div class="user-actions">
        {% if perms.user.can_manage_user %}
        <a href="{% url 'user:list-users' %}" class="back">
            <span class="icon">🔙</span> Voltar para Lista
        </a>
        {% endif %}
        <form action="{% url 'user:delete-account' user.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="delete">
                <span class="icon">🗑️</span> Deletar Conta
            </button>
        </form>
    </div>
</div>
{% endblock content %}